### ISSUE TITLE
thermal_engine.name is used twice

### ISSUE THREAD

**Issue by Handfeger** [Vswe/SC2_lang#19]
`thermal_engine.name` is used for the Termal Engine as well for 'Upgrade: Thermal Engine'

Lines: 264 and 425 in en_US.lang

The Engine is now called Upgrade: Thermal Engine

**Comment by Vswe** [comment]
The upgrade one is now called thermal_engine_upgrade. It will be shown properly in beta 3 (whenever that is released)
